### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by Waver-Velvet** [ust-archive/ust-rankings#1]
This issue collects the ideas that have to be finished before releasing v1. If you have any good ideas, feel free to post it under this issue! 

- [x] Schedule: users can check their class schedule and import them into their own calendar apps.
- [x] Schedule: users can import their classes by copying the SIS page.
- [x] Schedule: users can automatically get webcal link copied when they click the import to calendar button.
- [ ] Schedule: users can exclude the holidays on the imported class schedule
- [ ] Schedule: users can check the trend of classes' quota.
